project:
  name: xray-aws-security-hub
  owner: partner-team@jfrog.com
  s3_object_acl: public-read
  s3_regional_buckets: True
  regions:
    - us-west-1

tests:

  security-hub:
    parameters:
      S3BucketName: "$[taskcat_autobucket]"
      S3KeyPrefix: "xray-aws-security-hub"
    template: cft/security-hub.yaml

  lambdas:
    template: cft/lambda.yaml

  sqsqueues:
    template: cft/sqs-queue.yaml