AWSTemplateFormatVersion: '2010-09-09'
Description: "CFT creates two SQS FIFO queues (source queue and DL queue) to process Xray issues information."

Parameters:
  AlarmEmail:
    Default: "jane.doe@example.com"
    Description: "Email address to notify of operational issues."
    Type: String
#  LambdaMappingTransformerArn:
#    Type: String
#    Description: Arn for the Mapping Transformer lambda

Resources:
  XraySourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: XraySourceQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
      VisibilityTimeout: 120
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "XrayDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  XrayDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DeadLetterQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Ref: "AlarmEmail"
          Protocol: "email"
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if queue depth increases to more than 10 messages."
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value:
            Fn::GetAtt:
              - "XraySourceQueue"
              - "QueueName"
      Statistic: "Sum"
      Period: "300"
      EvaluationPeriods: "1"
      Threshold: "10"
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Ref: "AlarmTopic"
      InsufficientDataActions:
        - Ref: "AlarmTopic"
Outputs:
  XraySourceQueueName:
    Description: The name of the queue
    Value: !GetAtt XraySourceQueue.QueueName
  XraySourceQueueURL:
    Description: The URL of the queue
    Value: !Ref XraySourceQueue
  XraySourceQueueARN:
    Description: The ARN of the queue
    Value: !GetAtt XraySourceQueue.Arn
# Trying to assign export name to use it in Lambda stack
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-XraySourceQueueARN"
  XrayDeadLetterQueueName:
    Description: The name of the queue
    Value: !GetAtt XrayDeadLetterQueue.QueueName
  XrayDeadLetterQueueURL:
    Description: The URL of the queue
    Value: !Ref XrayDeadLetterQueue
  XrayDeadLetterQueueARN:
    Description: The ARN of the queue
    Value: !GetAtt XrayDeadLetterQueue.Arn
