AWSTemplateFormatVersion: "2010-09-09"
Description: "JFrog Xray AWS Security Hub Integration S3 bucket for Serverless Application Repository"

Parameters:
  S3BucketName:
    Type: String
    Description: Name of S3 bucket to store the artifacts for publishing to Serverless Application Repository
    Default: jfrog-xray-aws-security-hub

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Principal:
              Service: 'serverlessrepo.amazonaws.com'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - '/*'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
